FROM openjdk:8-jdk-alpine

LABEL maintainer="Vagner Romualdo"

COPY target/*.jar /deployments/app.jar

#ENTRYPOINT ["java","-jar","/app.jar"]

ARG JVM_MEMORY_MIN_SIZE=-Xmx64m
ARG JVM_MEMORY_MAX_SIZE=-Xms64m
ARG JVM_CONFIG_VM_OPTIONS=-XX:+UnlockExperimentalVMOptions
ARG JVM_CONFIG_PROC_COUNT=-XX:ActiveProcessorCount=2
ARG JVM_CONFIG_XSS=-Xss256k
ARG JVM_GARBAGE_CONF_SURVIVOR_RATIO=-XX:SurvivorRatio=4
ARG JVM_GARBAGE_CONF_TARGET_SURVIVOR_RATIO=-XX:TargetSurvivorRatio=90
ARG JVM_GARBAGE_CONF_MIN_HEAP=-XX:MinHeapFreeRatio=25

EXPOSE 8080

CMD java $JVM_MEMORY_MIN_SIZE $JVM_MEMORY_MAX_SIZE  $JVM_CONFIG_VM_OPTIONS $JVM_CONFIG_PROC_COUNT $JVM_CONFIG_XSS $JVM_GARBAGE_CONF_SURVIVOR_RATIO $JVM_GARBAGE_CONF_TARGET_SURVIVOR_RATIO $JVM_GARBAGE_CONF_MIN_HEAP -jar /deployments/app.jar